"""initial

Revision ID: 0fc0b61af0a0
Revises: ef7dc8eaafe0
Create Date: 2026-06-11 09:49:21.647860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fc0b61af0a0'
down_revision: Union[str, Sequence[str], None] = 'ef7dc8eaafe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bloques_placa', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('circuitos', 'descripcion',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('circuitos', 'cantidad',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('circuitos', 'info_detallada',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('circuitos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagramas', 'marca',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('diagramas', 'modelo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('diagramas', 'tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('diagramas', 'gdrive_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('diagramas', 'nombre_archivo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('diagramas', 'ultima_sync',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ic_compatibilidad', 'fabricante',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ic_compatibilidad', 'modelo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ic_compatibilidad', 'compatibles',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ic_marcas', 'marking',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ic_marcas', 'modelo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ic_marcas', 'fabricante',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ic_marcas', 'funcion',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ic_marcas', 'compatibilidad',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones', 'valor_esperado',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones', 'notas',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('mediciones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mediciones_placa', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones_placa', 'valor_esperado',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones_placa', 'categoria',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones_placa', 'ic_referencia',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones_placa', 'notas',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('mediciones_placa', 'bloque',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones_placa', 'checked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('mediciones_placa', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('mediciones_placa', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notas_placa', 'bloque',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('notas_placa', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('notas_placa', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ordenes', 'placa',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ordenes', 'falla',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ordenes', 'diagnostico',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ordenes', 'proceso',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ordenes', 'solucion',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ordenes', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'en_curso'::character varying"))
    op.alter_column('ordenes', 'resultado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'n/a'::character varying"))
    op.alter_column('ordenes', 'tipo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ordenes', 'puntaje',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('ordenes', 'tipo_equipo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ordenes', 'marca',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ordenes', 'modelo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ordenes', 'checklist',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'::text"))
    op.alter_column('ordenes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_ordenes_tenant_numero', 'ordenes', ['tenant_id', 'numero'])
    op.alter_column('placas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('puntajes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('referencias', 'contenido_html',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('referencias', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reparaciones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sesiones_reparacion', 'notas',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('sesiones_reparacion', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'activa'::character varying"))
    op.alter_column('sesiones_reparacion', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('soluciones', 'falla',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('soluciones', 'solucion',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('soluciones', 'ics',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_server_default=sa.text("'[]'::character varying"))
    op.alter_column('soluciones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('tenants_slug_key'), 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.alter_column('tipos_equipo', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('tipos_equipo', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.create_unique_constraint(op.f('tenants_slug_key'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('soluciones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('soluciones', 'ics',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_server_default=sa.text("'[]'::character varying"))
    op.alter_column('soluciones', 'solucion',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('soluciones', 'falla',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('sesiones_reparacion', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sesiones_reparacion', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'activa'::character varying"))
    op.alter_column('sesiones_reparacion', 'notas',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('reparaciones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('referencias', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('referencias', 'contenido_html',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('puntajes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('placas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_ordenes_tenant_numero', 'ordenes', type_='unique')
    op.alter_column('ordenes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ordenes', 'checklist',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'::text"))
    op.alter_column('ordenes', 'modelo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ordenes', 'marca',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ordenes', 'tipo_equipo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ordenes', 'puntaje',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('ordenes', 'tipo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ordenes', 'resultado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'n/a'::character varying"))
    op.alter_column('ordenes', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'en_curso'::character varying"))
    op.alter_column('ordenes', 'solucion',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ordenes', 'proceso',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ordenes', 'diagnostico',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ordenes', 'falla',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ordenes', 'placa',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('notas_placa', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notas_placa', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('notas_placa', 'bloque',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones_placa', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mediciones_placa', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('mediciones_placa', 'checked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('mediciones_placa', 'bloque',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones_placa', 'notas',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('mediciones_placa', 'ic_referencia',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones_placa', 'categoria',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones_placa', 'valor_esperado',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones_placa', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mediciones', 'notas',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('mediciones', 'valor_esperado',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mediciones', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ic_marcas', 'compatibilidad',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ic_marcas', 'funcion',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ic_marcas', 'fabricante',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ic_marcas', 'modelo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ic_marcas', 'marking',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ic_compatibilidad', 'compatibles',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ic_compatibilidad', 'modelo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ic_compatibilidad', 'fabricante',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('diagramas', 'ultima_sync',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('diagramas', 'nombre_archivo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('diagramas', 'gdrive_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('diagramas', 'tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('diagramas', 'modelo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('diagramas', 'marca',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('circuitos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('circuitos', 'info_detallada',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('circuitos', 'cantidad',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('circuitos', 'descripcion',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('bloques_placa', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
